export const IMAGES = {
  logo: { src: "/logo.png", w: 32, h: 32 },
  pitch: { src: "/pitch.png", w: 1400, h: 1547 },
  arsenal_gk: { src: "/jerseys/arsenal-gk.webp", w: 66, h: 87 },
  arsenal: { src: "/jerseys/arsenal.webp", w: 66, h: 87 },
  aston_villa_gk: { src: "/jerseys/aston-villa-gk.webp", w: 66, h: 87 },
  aston_villa: { src: "/jerseys/aston-villa.webp", w: 66, h: 87 },
  bournemouth_gk: { src: "/jerseys/bournemouth-gk.webp", w: 66, h: 87 },
  bournemouth: { src: "/jerseys/bournemouth.webp", w: 66, h: 87 },
  brentford: { src: "/jerseys/brentford.webp", w: 66, h: 87 },
  brentford_gk: { src: "/jerseys/brentford-gk.webp", w: 66, h: 87 },
  brighton_gk: { src: "/jerseys/brighton-gk.webp", w: 66, h: 87 },
  brighton: { src: "/jerseys/brighton.webp", w: 66, h: 87 },
  chelsea: { src: "/jerseys/chelsea.webp", w: 66, h: 87 },
  chelsea_gk: { src: "/jerseys/chelsea-gk.webp", w: 66, h: 87 },
  crystal_palace_gk: { src: "/jerseys/crystal-palace-gk.webp", w: 66, h: 87 },
  crystal_palace: { src: "/jerseys/crystal-palace.webp", w: 66, h: 87 },
  everton: { src: "/jerseys/everton.webp", w: 66, h: 87 },
  everton_gk: { src: "/jerseys/everton-gk.webp", w: 66, h: 87 },
  fulham_gk: { src: "/jerseys/fulham-gk.webp", w: 66, h: 87 },
  fulham: { src: "/jerseys/fulham.webp", w: 66, h: 87 },
  liverpool: { src: "/jerseys/liverpool.webp", w: 66, h: 87 },
  liverpool_gk: { src: "/jerseys/liverpool-gk.webp", w: 66, h: 87 },
  man_city_gk: { src: "/jerseys/man-city-gk.webp", w: 66, h: 87 },
  man_city: { src: "/jerseys/man-city.webp", w: 66, h: 87 },
  man_united_gk: { src: "/jerseys/man-united-gk.webp", w: 66, h: 87 },
  man_united: { src: "/jerseys/man-united.webp", w: 66, h: 87 },
  newcastle: { src: "/jerseys/newcastle.webp", w: 66, h: 87 },
  newcastle_gk: { src: "/jerseys/newcastle-gk.webp", w: 66, h: 87 },
  nottingham_forest_gk: {
    src: "/jerseys/nottingham-forest-gk.webp",
    w: 66,
    h: 87,
  },
  nottingham_forest: { src: "/jerseys/nottingham-forest.webp", w: 66, h: 87 },
  tottenham: { src: "/jerseys/tottenham.webp", w: 66, h: 87 },
  tottenham_gk: { src: "/jerseys/tottenham-gk.webp", w: 66, h: 87 },
  west_ham_gk: { src: "/jerseys/west-ham-gk.webp", w: 66, h: 87 },
  west_ham: { src: "/jerseys/west-ham.webp", w: 66, h: 87 },
  wolves: { src: "/jerseys/wolves.webp", w: 66, h: 87 },
  wolves_gk: { src: "/jerseys/wolves-gk.webp", w: 66, h: 87 },
};
